# config context path to "/" by setting an empty string
server: 
  contextPath: /autorizacao
  port: 9000

# JACKSON
spring:
  application:
    name: auth-server
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/autenticacao
    username: postgres
    password: P123456
  jackson:
    serialization:
      INDENT_OUTPUT: true
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    org.springframework:
      security: DEBUG

    
